server:
  port: 8761
spring:
  application:
    name: DiscoveryServer
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    root: trace