spring:
  application:
    name: FIRST-CLIENT
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9090
logging:
  level:
    root: trace